# Generated by Django 3.2.23 on 2026-01-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_auto_20240911_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='ntfy_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
