# Generated by Django 3.2.23 on 2026-01-12 19:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_ntfy_notification_fields'),
        ('targetApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startScan', '0003_ntfy_notification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledScan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this scheduled scan', max_length=500)),
                ('cron_expression', models.CharField(help_text="Cron expression (e.g., '0 2 * * *' for daily at 2 AM)", max_length=100)),
                ('imported_subdomains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('out_of_scope_subdomains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('starting_point_path', models.CharField(blank=True, max_length=200, null=True)),
                ('excluded_paths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Paused'), (2, 'Stopped')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('ntfy_enabled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scheduled_scans', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, help_text='Single target domain (leave empty if scanning organization)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_scans', to='targetApp.domain')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization for multi-target scanning', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_scans', to='targetApp.organization')),
                ('scan_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_scans', to='scanEngine.enginetype')),
            ],
            options={
                'verbose_name': 'Scheduled Scan',
                'verbose_name_plural': 'Scheduled Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledScanRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baseline_updated', models.BooleanField(default=False)),
                ('new_findings_count', models.IntegerField(default=0)),
                ('notification_sent', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_run', to='startScan.scanhistory')),
                ('scheduled_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='startScan.scheduledscan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledScanBaseline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baseline_findings_count', models.IntegerField(default=0)),
                ('subdomains_count', models.IntegerField(default=0)),
                ('endpoints_count', models.IntegerField(default=0)),
                ('ports_count', models.IntegerField(default=0)),
                ('technologies_count', models.IntegerField(default=0)),
                ('emails_count', models.IntegerField(default=0)),
                ('employees_count', models.IntegerField(default=0)),
                ('dorks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_for', to='startScan.scanhistory')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_scan_baselines', to='targetApp.domain')),
                ('scheduled_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='startScan.scheduledscan')),
            ],
            options={
                'verbose_name': 'Scheduled Scan Baseline',
                'verbose_name_plural': 'Scheduled Scan Baselines',
                'unique_together': {('scheduled_scan', 'domain')},
            },
        ),
    ]
