# Generated by Django 3.2.23 on 2026-01-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chaosapikey_hackeroneapikey_inappnotification_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='ntfy_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='ntfy_include_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='ntfy_topic',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
