# Generated by Django 3.2.23 on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_ntfy_notification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='C99APIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HunterIOAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DehashedAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShodanAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
