# Generated by Django 3.2.23 on 2026-01-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0002_hackerone_send_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ntfy_server_url',
            field=models.CharField(blank=True, default='https://ntfy.sh', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to_ntfy',
            field=models.BooleanField(default=False),
        ),
    ]
